### ISSUE TITLE
Consider using requests retries

### ISSUE THREAD

**Issue by danlamanna** [CapitalRegionVaccine/CapitalRegionVaccine#36]
I'm not sure how fragile the services are, but maybe automatic [retries](https://www.peterbe.com/plog/best-practice-with-retries-with-requests) would be useful.

**Comment by CapitalRegionVaccine** [comment]
Surprisingly haven't had too many issues with the services (maybe one or 2 a day).  Honestly I'd like to move the whole thing from requests to aiohttp but haven't had the time.
